sonar.projectKey=The-Johnnie-Walkers_peerly-user-management
sonar.organization=the-johnnie-walkers
sonar.projectName=Backend Users
sonar.sources=src
sonar.exclusions=\
  **/*.spec.ts,\
  **/node_modules/**,\
  **/dist/**,\
  **/coverage/**,\
  **/seed-interests.ts,\
  **/main.ts,\
  **/*.module.ts,\
  **/*.schema.ts,\
  **/*.dto.ts,\
  **/*.mapper.ts,\
  **/repositories/**,\
  **/messaging/**,\
  **/domain/entities/**,\
  **/domain/ports/**,\
  **/domain/enums/**,\
  **/infrastructure/adapters/out/**,\
  **/controllers/activity.controller.ts,\
  **/controllers/community.controller.ts,\
  **/controllers/connection.controller.ts,\
  **/controllers/interest.controller.ts,\
  **/controllers/user-message.controller.ts,\
  **/storage/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=\
  **/main.ts,\
  **/*.module.ts,\
  **/*.schema.ts,\
  **/*.dto.ts,\
  **/*.mapper.ts,\
  **/repositories/**,\
  **/messaging/**,\
  **/domain/entities/**,\
  **/domain/ports/**,\
  **/domain/enums/**,\
  **/infrastructure/adapters/out/**,\
  **/controllers/activity.controller.ts,\
  **/controllers/community.controller.ts,\
  **/controllers/connection.controller.ts,\
  **/controllers/interest.controller.ts,\
  **/controllers/user-message.controller.ts,\
  **/storage/**,\
  **/seed-interests.ts,\
  **/shared/**
