export enum Program {
    SYSTEMS_ENGINEERING = 'SYSTEMS_ENGINEERING',
    CIVIL_ENGINEERING = 'CIVIL_ENGINEERING',
    INDUSTRIAL_ENGINEERING = 'INDUSTRIAL_ENGINEERING',
    CYBERSECURITY_ENGINEERING = 'CYBERSECURITY_ENGINEERING',
    MECHANICAL_ENGINEERING = 'MECHANICAL_ENGINEERING',
    ELECTRICAL_ENGINEERING = 'ELECTRICAL_ENGINEERING',
    BIOMEDICAL_ENGINEERING = 'BIOMEDICAL_ENGINEERING',
    AI_ENGINEERING = 'AI_ENGINEERING',
    ELECTRONICAL_ENGINEERING = 'ELECTRONICAL_ENGINEERING',
    ENVIRONMENTAL_ENGINEERING = 'ENVIRONMENTAL_ENGINEERING',
    BIOTECHNOLOGY_ENGINEERING = 'BIOTECHNOLOGY_ENGINEERING',
    STATISTIC_ENGINEERING = 'STATISTIC_ENGINEERING',
    ECONOMY = 'ECONOMY',
    MATHEMATICS = 'MATHEMATICS',
    ENTERPRISE_ADMINISTRATION = 'ENTERPRISE_ADMINISTRATION'
}
